### ISSUE TITLE
Provide a mod.json URL for each mod

### ISSUE THREAD

**Issue by daftmugi** [ngld/fsnebula#8]
Since Knossos has become the de facto installer, launcher, and source of information about how to install mods (mod.json), it would be invaluable to folks to have easy access to the mod.json files.

I propose the following URL scheme: `fsnebula.org/mod/<modname>/mod.json`

1. This would help folks who cannot get Knossos installed.
2. This would help folks who choose not to install Knossos.
3. This would help folks troubleshoot why a mod is not installing or running correctly.

**Comment by EatThePath** [comment]
Since not all mods require the current version of their dependencies supporting this fully also requires exposing older versions of mods to manual download, something that may already be possible but certainly isn't well advertised.
